templatepath: templates
machinepath: machines
baseurl: http://127.0.0.1:9090
params:
    apt_hostname: "us.archive.ubuntu.com"
    apt_path: "/ubuntu/"
    dns_nameservers: "8.8.8.8"
    ntp_server: "us.pool.ntp.org"
default_cmdline: "netcfg/get_nameservers=8.8.8.8 netcfg/disable_dhcp=true interface={{ machine.Network.0.Name }} ksdevice={{ machine.Network.0.Name }} netcfg/get_ipaddress={{ machine.Network.0.IPAddress }} netcfg/get_gateway={{ machine.Network.0.Gateway }} netcfg/get_netmask={{ machine.Network.0.Netmask }} url={{ BaseURL }}/template/preseed/{{ Hostname }}/{{ Token }} ramdisk_size=10800 root=/dev/rd/0 rw auto hostname={{ Hostname }} console-setup/ask_detect=false console-setup/layout=USA console-setup/variant=USA keyboard-configuration/layoutcode=us localechooser/translation/warn-light=true localechooser/translation/warn-severe=true locale=en_US"
default_kernel: linux
default_image_url: http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/
default_initrd: initrd.gz